### ISSUE TITLE
Make 'event' field in EventContext public

### ISSUE THREAD

**Issue by liuwb** [cloudshiftinc/aws-lambda-demux#2]
type EventContext struct {
	event           map[string]any
	resourceContext map[string]any
}

Both 'event' and 'resourceContext' are private fields that cannot be accessed in Factory method. Please make them public.

**Comment by cloudshiftchris** [comment]
Thanks for noting that; it's been addressed in v0.2.1

**Comment by liuwb** [comment]
> Thanks for noting that; it's been addressed in v0.2.1

Readme sample code should also be updated accordingly.
